Revert "CI: Run tests in parallel by invoking pytest on GHA with xdist"
This reverts commit 9cb29e72b5aad24d10e557a279ba98842dc0027f.

It is still too early. The error raised is:

_gdbm.error: [Errno 11] Resource temporarily unavailable: '/home/runner/.cache/wetterdienst/dogpile/metaindex.dbm'

So, some components of `dogpile.cache` with the dbm backend are
apparently not thread- or multiprocess-safe yet. This has to be
improved.