CI/GHA: Run Windows tests on windows-2019 instead of windows-2022
Resolves those errors:

    OSError: [WinError 10013] An attempt was made to access a socket in
    a way forbidden by its access permissions